# --- Basic ---
port=6380
application.name=camellia-redis-proxy-server
proxy.mode=standalone
netty.transport.mode=auto

# --- Monitoring ---
monitor.enable=true
monitor.interval.seconds=10
console.port=16379
proxy.plugin.list=monitorPlugin,bigKeyPlugin,hotKeyPlugin

# --- Dynamic reload ---
dynamic.conf.reload.interval.seconds=2

# --- Route provider ---
route.conf.provider=multi_tenants_v1
multi.tenant.route.default.bid=1
multi.tenant.route.default.bgroup=default
multi.tenant.route.conf.reload.interval.millis=2000
multi.tenant.route.conf.remove.enable=true

# -- managed-tenants:start --
tenantApwd.password.1.default.route.conf=redis://@redis-pool-a:6379
tenantBpwd.password.2.default.route.conf=redis://@redis-pool-b:6379
# -- managed-tenants:end --
