apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-camellia-proxy-standalone-order
  labels:
    app: camellia-proxy-standalone-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camellia-proxy-standalone-order
  template:
    metadata:
      labels:
        app: camellia-proxy-standalone-order
    spec:
      enableServiceLinks: false
      containers:
      - name: container-camellia
        image: 48n6e/camellia-redis-proxy:1.4.0-jdk-21-0.0.1
        command:
        - java
        - -XX:+UseG1GC
        - -XX:+UseContainerSupport
        - -Dio.netty.tryReflectionSetAccessible=true
        - --add-opens
        - java.base/java.lang=ALL-UNNAMED
        - --add-opens
        - java.base/java.io=ALL-UNNAMED
        - --add-opens
        - java.base/java.math=ALL-UNNAMED
        - --add-opens
        - java.base/java.net=ALL-UNNAMED
        - --add-opens
        - java.base/java.nio=ALL-UNNAMED
        - --add-opens
        - java.base/java.security=ALL-UNNAMED
        - --add-opens
        - java.base/java.text=ALL-UNNAMED
        - --add-opens
        - java.base/java.time=ALL-UNNAMED
        - --add-opens
        - java.base/java.util=ALL-UNNAMED
        - --add-opens
        - java.base/jdk.internal.access=ALL-UNNAMED
        - --add-opens
        - java.base/jdk.internal.misc=ALL-UNNAMED
        - --add-opens
        - java.base/sun.net.util=ALL-UNNAMED
        - -Xms128m
        - -Xmx512m
        - -server
        - org.springframework.boot.loader.launch.JarLauncher
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: '1'
        ports:
        - containerPort: 6380
          name: redis
          protocol: TCP
        - containerPort: 16379
          name: console
          protocol: TCP
        env:
        - name: LOGGING_LEVEL_ROOT
          value: INFO
        - name: LOGGING_LEVEL_COM_NETEASE_NIM_CAMELLIA_REDIS_PROXY
          value: INFO
        volumeMounts:
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/camellia-redis-proxy.properties
          subPath: camellia-redis-proxy-standalone-service-order.properties
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/logback.xml
          subPath: logback.xml
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/resource-service-order.json
          subPath: resource-service-order.json
      volumes:
      - name: cm-db-camellia
        configMap:
          name: cm-db-camellia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-camellia-proxy-standalone-payment
  labels:
    app: camellia-proxy-standalone-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camellia-proxy-standalone-payment
  template:
    metadata:
      labels:
        app: camellia-proxy-standalone-payment
    spec:
      enableServiceLinks: false
      containers:
      - name: container-camellia
        image: 48n6e/camellia-redis-proxy:1.4.0-jdk-21-0.0.1
        command:
        - java
        - -XX:+UseG1GC
        - -XX:+UseContainerSupport
        - -Dio.netty.tryReflectionSetAccessible=true
        - --add-opens
        - java.base/java.lang=ALL-UNNAMED
        - --add-opens
        - java.base/java.io=ALL-UNNAMED
        - --add-opens
        - java.base/java.math=ALL-UNNAMED
        - --add-opens
        - java.base/java.net=ALL-UNNAMED
        - --add-opens
        - java.base/java.nio=ALL-UNNAMED
        - --add-opens
        - java.base/java.security=ALL-UNNAMED
        - --add-opens
        - java.base/java.text=ALL-UNNAMED
        - --add-opens
        - java.base/java.time=ALL-UNNAMED
        - --add-opens
        - java.base/java.util=ALL-UNNAMED
        - --add-opens
        - java.base/jdk.internal.access=ALL-UNNAMED
        - --add-opens
        - java.base/jdk.internal.misc=ALL-UNNAMED
        - --add-opens
        - java.base/sun.net.util=ALL-UNNAMED
        - -Xms128m
        - -Xmx512m
        - -server
        - org.springframework.boot.loader.launch.JarLauncher
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: '1'
        ports:
        - containerPort: 6380
          name: redis
          protocol: TCP
        - containerPort: 16379
          name: console
          protocol: TCP
        volumeMounts:
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/camellia-redis-proxy.properties
          subPath: camellia-redis-proxy-standalone-service-payment.properties
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/logback.xml
          subPath: logback.xml
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/resource-service-payment.json
          subPath: resource-service-payment.json
      volumes:
      - name: cm-db-camellia
        configMap:
          name: cm-db-camellia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-camellia-proxy-standalone-search
  labels:
    app: camellia-proxy-standalone-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camellia-proxy-standalone-search
  template:
    metadata:
      labels:
        app: camellia-proxy-standalone-search
    spec:
      enableServiceLinks: false
      containers:
      - name: container-camellia
        image: 48n6e/camellia-redis-proxy:1.4.0-jdk-21-0.0.1
        command:
        - java
        - -XX:+UseG1GC
        - -XX:+UseContainerSupport
        - -Dio.netty.tryReflectionSetAccessible=true
        - --add-opens
        - java.base/java.lang=ALL-UNNAMED
        - --add-opens
        - java.base/java.io=ALL-UNNAMED
        - --add-opens
        - java.base/java.math=ALL-UNNAMED
        - --add-opens
        - java.base/java.net=ALL-UNNAMED
        - --add-opens
        - java.base/java.nio=ALL-UNNAMED
        - --add-opens
        - java.base/java.security=ALL-UNNAMED
        - --add-opens
        - java.base/java.text=ALL-UNNAMED
        - --add-opens
        - java.base/java.time=ALL-UNNAMED
        - --add-opens
        - java.base/java.util=ALL-UNNAMED
        - --add-opens
        - java.base/jdk.internal.access=ALL-UNNAMED
        - --add-opens
        - java.base/jdk.internal.misc=ALL-UNNAMED
        - --add-opens
        - java.base/sun.net.util=ALL-UNNAMED
        - -Xms128m
        - -Xmx512m
        - -server
        - org.springframework.boot.loader.launch.JarLauncher
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: '1'
        ports:
        - containerPort: 6380
          name: redis
          protocol: TCP
        - containerPort: 16379
          name: console
          protocol: TCP
        volumeMounts:
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/camellia-redis-proxy.properties
          subPath: camellia-redis-proxy-standalone-service-search.properties
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/logback.xml
          subPath: logback.xml
        - name: cm-db-camellia
          mountPath: /opt/camellia-redis-proxy/BOOT-INF/classes/resource-service-search.json
          subPath: resource-service-search.json
      volumes:
      - name: cm-db-camellia
        configMap:
          name: cm-db-camellia
