apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - consensus-redis.yaml
  - camellia-proxy-cluster-shared-auth-deployment.yaml
  - camellia-proxy-cluster-shared-auth-service.yaml
