apiVersion: v1
kind: Service
metadata:
  name: svc-camellia-proxy-order
  labels:
    app.kubernetes.io/name: camellia-proxy
    app.kubernetes.io/component: metrics
    camellia_topology: service-order
    monitoring.camellia.io/enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "16379"
    prometheus.io/path: "/prometheus"
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - name: redis
      port: 6380
      targetPort: 6380
      nodePort: 30780
    - name: console
      port: 16379
      targetPort: 16379
      nodePort: 30790
  selector:
    app: camellia-proxy-order
---
apiVersion: v1
kind: Service
metadata:
  name: svc-camellia-proxy-payment
  labels:
    app.kubernetes.io/name: camellia-proxy
    app.kubernetes.io/component: metrics
    camellia_topology: service-payment
    monitoring.camellia.io/enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "16379"
    prometheus.io/path: "/prometheus"
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - name: redis
      port: 6380
      targetPort: 6380
      nodePort: 30781
    - name: console
      port: 16379
      targetPort: 16379
      nodePort: 30791
  selector:
    app: camellia-proxy-payment
---
apiVersion: v1
kind: Service
metadata:
  name: svc-camellia-proxy-search
  labels:
    app.kubernetes.io/name: camellia-proxy
    app.kubernetes.io/component: metrics
    camellia_topology: service-search
    monitoring.camellia.io/enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "16379"
    prometheus.io/path: "/prometheus"
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - name: redis
      port: 6380
      targetPort: 6380
      nodePort: 30782
    - name: console
      port: 16379
      targetPort: 16379
      nodePort: 30792
  selector:
    app: camellia-proxy-search
