apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - camellia-proxy-standalone-shared-auth-deployment.yaml
  - camellia-proxy-standalone-shared-auth-service.yaml
