apiVersion: v1
kind: Service
metadata:
  name: svc-camellia-proxy-standalone
  labels:
    app.kubernetes.io/name: camellia-proxy
    app.kubernetes.io/component: metrics
    camellia_topology: standalone
    monitoring.camellia.io/enabled: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "16379"
    prometheus.io/path: "/prometheus"
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - name: redis
      protocol: TCP
      port: 6380
      targetPort: 6380
      nodePort: 30581
    - name: console
      protocol: TCP
      port: 16379
      targetPort: 16379
      nodePort: 30582
  selector:
    app: camellia-proxy-standalone