apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-db-camellia
data:

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="60 seconds" debug="false">
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %thread %X %logger{36}:%L - %msg%n</pattern>
        </encoder>
      </appender>

      <logger name="com.netease.nim" level="INFO" additivity="false">
        <appender-ref ref="STDOUT" />
      </logger>

      <!-- enable debug khi cần -->
      <!-- <logger name="com.netease.nim.camellia.redis.proxy" level="DEBUG"/> -->

      <root level="INFO">
        <appender-ref ref="STDOUT" />
      </root>
    </configuration>

  camellia-redis-proxy.properties: |
    proxy.cluster.mode.nodes=ip:port@cport
    proxy.cluster.mode.heartbeat.interval.seconds=5
    proxy.cluster.mode.heartbeat.timeout.seconds=20

  camellia-redis-proxy-shared-auth.properties: |
    port=6380
    application.name=camellia-redis-proxy-shared-auth
    proxy.mode=standalone
    netty.transport.mode=auto

    monitor.enable=true
    monitor.interval.seconds=10
    console.port=16379
    proxy.plugin.list=monitorPlugin,bigKeyPlugin,hotKeyPlugin

    dynamic.conf.reload.interval.seconds=2

    route.conf.provider=multi_tenants_v1
    multi.tenant.route.default.bid=101
    multi.tenant.route.default.bgroup=prod
    multi.tenant.route.conf.reload.interval.millis=2000
    multi.tenant.route.conf.remove.enable=true

    svcOrderPwd.password.101.prod.route.conf={"type":"sharding","operation":{"bucketSize":3,"operationMap":{"0":{"read":"redis://@redis-pool-1:6379","type":"rw_separate","write":"redis://@redis-pool-1:6379"},"1":{"read":"redis://@redis-pool-2:6379","type":"rw_separate","write":"redis://@redis-pool-2:6379"},"2":{"read":"redis://@redis-pool-3:6379","type":"rw_separate","write":"redis://@redis-pool-3:6379"}}}}
    svcPaymentPwd.password.102.prod.route.conf={"type":"sharding","operation":{"bucketSize":3,"operationMap":{"0":{"read":"redis://@redis-pool-4:6379","type":"rw_separate","write":"redis://@redis-pool-4:6379"},"1":{"read":"redis://@redis-pool-5:6379","type":"rw_separate","write":"redis://@redis-pool-5:6379"},"2":{"read":"redis://@redis-pool-6:6379","type":"rw_separate","write":"redis://@redis-pool-6:6379"}}}}
    svcSearchPwd.password.103.prod.route.conf={"type":"sharding","operation":{"bucketSize":3,"operationMap":{"0":{"read":"redis://@redis-pool-7:6379","type":"rw_separate","write":"redis://@redis-pool-7:6379"},"1":{"read":"redis://@redis-pool-8:6379","type":"rw_separate","write":"redis://@redis-pool-8:6379"},"2":{"read":"redis://@redis-pool-9:6379","type":"rw_separate","write":"redis://@redis-pool-9:6379"}}}}

  application-cluster.yml: |
    server:
      port: 6380
    spring:
      application:
        name: camellia-redis-proxy-server
    camellia-redis-proxy:
      console-port: 16378
      cport: 16380
      cport-password: camellia_cport_pass
      password: camellia_admin_pass
      cluster-mode-enable: true
      sentinel-mode-enable: false
      monitor-enable: true  
      monitor-interval-seconds: 60
      cluster-mode-provider-class-name: com.netease.nim.camellia.redis.proxy.cluster.provider.ConsensusProxyClusterModeProvider
      netty:
        boss-thread: 1
        worker-thread: 8
      plugins:
        - monitorPlugin
        - bigKeyPlugin
        - hotKeyPlugin
        - hotKeyCachePlugin
      config:
        "check.redis.resource.valid.not.active.threshold.sceonds": 300
        "proxy.cluster.mode.command.move.always": true
        "cluster.mode.consensus.leader.selector.class.name": "com.netease.nim.camellia.redis.proxy.cluster.provider.RedisConsensusLeaderSelector"
        "redis.consensus.leader.selector.redis.url": "redis://@xxxx:6379"
        "redis.consensus.leader.selector.redis.key": "camellia:proxy:leader:slotmap:v1"
      transpond:
        type: local 
        local:
          type: complex
          json-file: resource-sharding-singlewrite-multiread.json
        redis-conf:
          sharding-func: com.netease.nim.camellia.core.client.env.CRC16HashTagShardingFunc
          redis-cluster-max-attempts: 5
          close-idle-connection: true
          check-idle-connection-threshold-seconds: 600
          close-idle-connection-delay-seconds: 60
          preheat: true
          heartbeat-interval-seconds: 60 
          heartbeat-timeout-millis: 10000
          connect-timeout-millis: 1000
          fail-count-threshold: 5
          fail-ban-millis: 5000


  application-standalone.yml: |
    server:
      port: 6380

    spring:
      application:
        name: camellia-redis-proxy-server

    camellia-redis-proxy:

      console-port: 16379
      password: camellia_admin_pass

      # ======================
      # NETTY THREAD (4 vCPU)
      # ======================
      netty:
        boss-thread: 1
        worker-thread: 8   # ~2x CPU → optimal

      # ======================
      # MONITOR
      # ======================
      monitor-enable: true
      monitor-interval-seconds: 10

      plugins:
        - monitorPlugin
        - bigKeyPlugin
        - hotKeyPlugin
        - hotKeyCachePlugin

      # ======================
      # GLOBAL CONFIG
      # ======================
      config:
        "check.redis.resource.valid.not.active.threshold.sceonds": 300
        "redis.fail.fast.enable": true
        "redis.fail.fast.threshold": 5

      # ======================
      # TRANSpond (ROUTING)
      # ======================
      transpond:
        type: local

        local:
          type: complex
          json-file: resource-sharding-singlewrite-multiread.json

        redis-conf:

          # ======================
          # SHARDING
          # ======================
          sharding-func: com.netease.nim.camellia.core.client.env.CRC16HashTagShardingFunc

          # ======================
          # CONNECTION POOL
          # ======================
          min-idle: 100
          max-idle: 400
          max-total: 400
          max-wait-millis: 3000

          # ======================
          # TIMEOUT
          # ======================
          timeout-millis: 2000
          connect-timeout-millis: 1000

          # ======================
          # CONNECTION LIFECYCLE
          # ======================
          preheat: true
          close-idle-connection: true
          check-idle-connection-threshold-seconds: 300
          close-idle-connection-delay-seconds: 30

  application-service-order.yml: |
    server:
      port: 6380
    spring:
      application:
        name: camellia-redis-proxy-order
    camellia-redis-proxy:
      console-port: 16379
      password: camellia_admin_pass
      netty:
        boss-thread: 1
        worker-thread: 4
      monitor-enable: true
      monitor-interval-seconds: 10
      plugins:
        - monitorPlugin
        - bigKeyPlugin
        - hotKeyPlugin
      transpond:
        type: local
        local:
          type: complex
          json-file: resource-service-order.json
        redis-conf:
          sharding-func: com.netease.nim.camellia.core.client.env.CRC16HashTagShardingFunc
          preheat: true
          close-idle-connection: true
          check-idle-connection-threshold-seconds: 300
          close-idle-connection-delay-seconds: 30

  application-service-payment.yml: |
    server:
      port: 6380
    spring:
      application:
        name: camellia-redis-proxy-payment
    camellia-redis-proxy:
      console-port: 16379
      password: camellia_admin_pass
      netty:
        boss-thread: 1
        worker-thread: 4
      monitor-enable: true
      monitor-interval-seconds: 10
      plugins:
        - monitorPlugin
        - bigKeyPlugin
        - hotKeyPlugin
      transpond:
        type: local
        local:
          type: complex
          json-file: resource-service-payment.json
        redis-conf:
          sharding-func: com.netease.nim.camellia.core.client.env.CRC16HashTagShardingFunc
          preheat: true
          close-idle-connection: true
          check-idle-connection-threshold-seconds: 300
          close-idle-connection-delay-seconds: 30

  application-service-search.yml: |
    server:
      port: 6380
    spring:
      application:
        name: camellia-redis-proxy-search
    camellia-redis-proxy:
      console-port: 16379
      password: camellia_admin_pass
      netty:
        boss-thread: 1
        worker-thread: 4
      monitor-enable: true
      monitor-interval-seconds: 10
      plugins:
        - monitorPlugin
        - bigKeyPlugin
        - hotKeyPlugin
      transpond:
        type: local
        local:
          type: complex
          json-file: resource-service-search.json
        redis-conf:
          sharding-func: com.netease.nim.camellia.core.client.env.CRC16HashTagShardingFunc
          preheat: true
          close-idle-connection: true
          check-idle-connection-threshold-seconds: 300
          close-idle-connection-delay-seconds: 30

  application-key-routing.yml: |
    server:
      port: 6380
    spring:
      application:
        name: camellia-redis-proxy-key-routing
    camellia-redis-proxy:
      console-port: 16379
      password: camellia_admin_pass
      netty:
        boss-thread: 1
        worker-thread: 8
      monitor-enable: true
      monitor-interval-seconds: 10
      plugins:
        - monitorPlugin
        - bigKeyPlugin
        - hotKeyPlugin
      transpond:
        type: local
        local:
          type: complex
          json-file: resource-key-routing.json
        redis-conf:
          sharding-func: com.netease.nim.camellia.core.client.env.CRC16HashTagShardingFunc
          preheat: true
          close-idle-connection: true
          check-idle-connection-threshold-seconds: 300
          close-idle-connection-delay-seconds: 30

  resource-sharding-singlewrite-multiread.json: |
    {
      "type": "sharding",
      "operation": {
        "bucketSize": 3,
        "operationMap": {
          "0": {
            "read": {
              "resources": [
                "redis://@redis-pool-2:6379",
                "redis://@redis-pool-3:6379"
              ],
              "type": "random"
            },
            "type": "rw_separate",
            "write": "redis://@redis-pool-1:6379"
          },
          "1": {
            "read": {
              "resources": [
                "redis://@redis-pool-5:6379",
                "redis://@redis-pool-6:6379"
              ],
              "type": "random"
            },
            "type": "rw_separate",
            "write": "redis://@redis-pool-4:6379"
          },
          "2": {
            "read": {
              "resources": [
                "redis://@redis-pool-8:6379",
                "redis://@redis-pool-9:6379"
              ],
              "type": "random"
            },
            "type": "rw_separate",
            "write": "redis://@redis-pool-7:6379"
          }
        }
      }
    }


  resource-table.json: |
    {
      "type": "sharding",
      "operation": {
        "bucketSize": 9,
        "operationMap": {

          "0": { "read": "redis://@redis-pool-1:6379", "type": "rw_separate", "write": "redis://@redis-pool-1:6379" },
          "1": { "read": "redis://@redis-pool-2:6379", "type": "rw_separate", "write": "redis://@redis-pool-2:6379" },
          "2": { "read": "redis://@redis-pool-3:6379", "type": "rw_separate", "write": "redis://@redis-pool-3:6379" },

          "3": { "read": "redis://@redis-pool-4:6379", "type": "rw_separate", "write": "redis://@redis-pool-4:6379" },
          "4": { "read": "redis://@redis-pool-5:6379", "type": "rw_separate", "write": "redis://@redis-pool-5:6379" },
          "5": { "read": "redis://@redis-pool-6:6379", "type": "rw_separate", "write": "redis://@redis-pool-6:6379" },

          "6": { "read": "redis://@redis-pool-7:6379", "type": "rw_separate", "write": "redis://@redis-pool-7:6379" },
          "7": { "read": "redis://@redis-pool-8:6379", "type": "rw_separate", "write": "redis://@redis-pool-8:6379" },
          "8": { "read": "redis://@redis-pool-9:6379", "type": "rw_separate", "write": "redis://@redis-pool-9:6379" }

        }
      }
    }

  resource-service-order.json: |
    {
      "type": "simple",
      "operation": {
        "read": {
          "resources": [
            "redis://@redis-pool-2:6379",
            "redis://@redis-pool-3:6379"
          ],
          "type": "random"
        },
        "type": "rw_separate",
        "write": "redis://@redis-pool-1:6379"
      }
    }

  resource-service-payment.json: |
    {
      "type": "simple",
      "operation": {
        "read": {
          "resources": [
            "redis://@redis-pool-5:6379",
            "redis://@redis-pool-6:6379"
          ],
          "type": "random"
        },
        "type": "rw_separate",
        "write": "redis://@redis-pool-4:6379"
      }
    }

  resource-service-search.json: |
    {
      "type": "simple",
      "operation": {
        "read": {
          "resources": [
            "redis://@redis-pool-8:6379",
            "redis://@redis-pool-9:6379"
          ],
          "type": "random"
        },
        "type": "rw_separate",
        "write": "redis://@redis-pool-7:6379"
      }
    }

  resource-key-routing.json: |
    {
      "type": "sharding",
      "operation": {
        "bucketSize": 9,
        "operationMap": {
          "0": { "read": "redis://@redis-pool-1:6379", "type": "rw_separate", "write": "redis://@redis-pool-1:6379" },
          "1": { "read": "redis://@redis-pool-2:6379", "type": "rw_separate", "write": "redis://@redis-pool-2:6379" },
          "2": { "read": "redis://@redis-pool-3:6379", "type": "rw_separate", "write": "redis://@redis-pool-3:6379" },
          "3": { "read": "redis://@redis-pool-4:6379", "type": "rw_separate", "write": "redis://@redis-pool-4:6379" },
          "4": { "read": "redis://@redis-pool-5:6379", "type": "rw_separate", "write": "redis://@redis-pool-5:6379" },
          "5": { "read": "redis://@redis-pool-6:6379", "type": "rw_separate", "write": "redis://@redis-pool-6:6379" },
          "6": { "read": "redis://@redis-pool-7:6379", "type": "rw_separate", "write": "redis://@redis-pool-7:6379" },
          "7": { "read": "redis://@redis-pool-8:6379", "type": "rw_separate", "write": "redis://@redis-pool-8:6379" },
          "8": { "read": "redis://@redis-pool-9:6379", "type": "rw_separate", "write": "redis://@redis-pool-9:6379" }
        }
      }
    }
