apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-db-camellia
data:
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration scan="true" scanPeriod="60 seconds" debug="false">
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d %-5p %t %X %c{1}:%L - %m%n</pattern>
        </encoder>
      </appender>

      <logger name="com.netease.nim" level="INFO" additivity="false">
        <appender-ref ref="STDOUT" />
      </logger>

      <root level="INFO">
        <appender-ref ref="STDOUT" />
      </root>
    </configuration>

  application.yml: |
    server:
      port: 6380
    spring:
      application:
        name: camellia-redis-proxy-server
    camellia-redis-proxy:
      console-port: 16379
      monitor-enable: true
      monitor-interval-seconds: 60
      plugins:
        - monitorPlugin
        - bigKeyPlugin
        - hotKeyPlugin
      config:
        "check.redis.resource.valid.not.active.threshold.sceonds": 300
      transpond:
        type: local
        local:
          type: complex
          json-file: resource-table.json
        redis-conf:
          sharding-func: com.netease.nim.camellia.core.client.env.CRC16HashTagShardingFunc
          preheat: false
          close-idle-connection: true
          check-idle-connection-threshold-seconds: 600
          close-idle-connection-delay-seconds: 60

  resource-table.json: |
    {
      "type": "sharding",
      "operation": {
        "operationMap": {
          "0": {
            "read": "redis://@redis-pool-a:6379",
            "type": "rw_separate",
            "write": "redis://@redis-pool-a:6379"
          },
          "1": {
            "read": "redis://@redis-pool-b:6379",
            "type": "rw_separate",
            "write": "redis://@redis-pool-b:6379"
          },
          "2": {
            "read": "redis://@redis-pool-c:6379",
            "type": "rw_separate",
            "write": "redis://@redis-pool-c:6379"
          }
        },
        "bucketSize": 3
      }
    }
